electronic/urls.py
from django.conf.urls import url
from electronic import views
#from electronic.views import UserFormView
app_name = 'electronic'


urlpatterns =[
    url(r'^$', views.show_login, name='index'),
    url(r'^login/$', views.login_user, name = 'login'),
    url(r'^home/$', views.show_home, name='home'),
    url(r'^logout/$', views.logout_user, name='logout_user'),
    url(r'^about/$', views.show_about, name='about'),
    url(r'^contact/$', views.show_contact, name='contact'),
    url(r'^get_new_id/$', views.new_id, name='get_id'),
   #url(r'^replace_id/$', views.replace_id, name='rep_id'),
    url(r'^id_status/$', views.id_status, name='id_stat'),
    url(r'^registration_form/$', views.registration_form, name='registration_form'),
    url(r'^do_register/$', views.do_register, name = 'do_register'),
    url(r'^account_register/$', views.account_register, name='account_register'),
    url(r'^get_id_info/$', views.get_id_info, name='get_id_info'),
    url(r'^do_replace/$', views.do_replace, name='do_replace'),

]

myweb/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('electronic.urls', namespace='electronic'))

]

electronic/models.py
from django.db import models
from django.db.models.signals import post_save
from django.contrib.auth.models import User


class Person(models.Model):
    first_name = models.CharField(max_length=100)
    second_name = models.CharField(max_length=100)
    third_name = models.CharField(max_length=100)
    id_number = models.IntegerField(default=0)  # generate 8digit random unique number
    district_of_birth = models.CharField(max_length=100)
    date_of_birth = models.DateField()
    id_status = models.BooleanField(default=False)
    gender = models.CharField(max_length=100)
    user = models.OneToOneField(User, on_delete=models.CASCADE, primary_key=True, related_name='person')

    def __str__(self):
        return str(self.id_number)


class Replacement(models.Model):
    first_name = models.CharField(max_length=100)
    id_number = models.ForeignKey(Person, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=10)

electronic/forms.py
#from django.contrib.auth.models import Person
from django import forms
from .models import Person


class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput)

    class Meta:
        model=Person
        fields = ['first_name', 'second_name', 'third_name',
                  'email', 'password', ]

electronic/views.py
from django.contrib.auth import authenticate, login, logout
from django.core import urlresolvers
from django.http import HttpResponseRedirect, HttpResponse
from django.shortcuts import render, redirect
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Person, Replacement


def show_login(request):
    return render(request, 'electronic/login.html')


def login_user(request):
    postdata = request.POST.copy()
    username = postdata.get("username", "")
    password = postdata.get("password", "")
    user = authenticate(username=username, password=password)
    if user is not None and user.is_active:
        login(request, user)
        url = urlresolvers.reverse('electronic:home')
        return HttpResponseRedirect(url)
    else:
        error_msg = "check your username and password!"
        return render(request, 'electronic/login.html', locals())


def registration_form(request):
    return render(request, 'electronic/registration_form.html')


def show_home(request):
    person = Person.objects.all()
    return render(request, 'electronic/home.html', {'person': person})
    # return render(request, 'electronic/home.html')


def logout_user(request):
    logout(request)
    url = urlresolvers.reverse('electronic:index')
    return HttpResponseRedirect(url)


def show_about(request):
    return render(request, 'electronic/about.html')

def show_contact(request):
    return render(request, 'electronic/contact.html')


def new_id(request):
    return render(request, 'electronic/get_new_id.html')


def get_id_info(request):
    id_info = Person.objects.get(user = request.user)
    return render(request, 'electronic/replace_confirmation.html', {'id_info': id_info})


def do_replace(request):
    postdata = request.POST.copy()
    idno = postdata.get('idno', '')
    person = Person.objects.get(id_number=idno)
    phone_number = postdata.get('PhoneNumber')
    person.id_status = False
    replacement = Replacement()
    replacement.phone_number = phone_number
    replacement.first_name = person.first_name
    replacement.id_number = person
    replacement.save()
    return render(request, 'electronic/home.html')


def id_status(request):
    return render(request, 'electronic/id_status.html')


def get_queryset(request):
    person = Person.objects.all()
    return render(request, 'electronic/home.html', {'person': person})


def do_register(request):
    postdata = request.POST.copy()
    fname = postdata.get('fname', '')
    sname = postdata.get('sname', '')
    tname = postdata.get('tname', '')
    district_of_birth = postdata.get('district_of_birth', '')
    date_of_birth = postdata.get('date_of_birth', '')
    gender = postdata.get('gender', '')
    prev_person = Person.objects.latest('id_number')

    id_info = Person()
    id_info.first_name = fname
    id_info.second_name = sname
    id_info.third_name = tname
    id_info.district_of_birth = district_of_birth
    id_info.date_of_birth = date_of_birth
    id_info.gender = gender
    id_info.id_number = prev_person.id_number + 1
    print(request.user.username)

    id_info.user = request.user
    id_info.save()
    return render(request, 'electronic/get_new_id.html')


def account_register(request):
    postdata = request.POST.copy()
    username = postdata.get('username', '')
    email = postdata.get('email', '')
    password = postdata.get('password', '')
    newuser = User()
    newuser.username = username
    newuser.password = password
    newuser.email = email
    newuser.save()
    return render(request, 'electronic/login.html')

electronic/templates/electronic/about.html
{% extends 'electronic/base.html' %}

{% block title %}about{% endblock %}

{% block content %}
<div class="raw">
    <h2>learn more about us...</h2>
    <!-- about us content goes here -->
    <p>Apart from the innovative purposes and all that security cliche you hear about everyday... Electronic has
        something<br>
        far much better in mind. This purpose if for everyone to be able to access government services from everywhere
        they are.<br>
        Equity... that's the word. This is to enable everyone who is of the legal age of applying for the national
        identification
        <br> card ample time and quick access to do so without having to gro through all the trouble it entails.</p>
    <br>

    <h2>Inspiration</h2>
    <p>What inspired me to come up with this project was the urge to solve problems. I always saw people having to wait
        on
        <br> lines for hours before they are tended to by the officials. This was so bad because i went through the
        same.
        <br> So the reason mostly is to try and make life much better and basic things easier to access and do from
        home. <br>
        There was a particular thing that led me to come up with this idea. I, just like all other kids in my age group
        <br>
        had just cleared my high school and went to apply for the national identification card as is the kenyan
        "custom".
        <br> I went to the offices early enough only to find few kids there waiting for the officials to open their
        offices.
        <br> They seemed to tae their time and did not care how long we waited. They soon got set up and the processes
        begun.
        <br> They went on for a while and then it was afternoon. So the officials had to leave for lunch and we had to
        stay
        <br> there and wait for them to finish. That lasted roughly two hours. they soon came and then we completed the
        <br>
        application process. I was very frustrated by the act. To make it worse i couldn't do anything to change the
        situation,
        <br> but i said to myself some day i will make changes and impact the lifes of many and give power back to the
        people.</p>
    <br>
    <h2>Ambition</h2>
    <p></p>
    <br>
</div>
{% endblock %}

electronic/templates/electronic/base.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>{% block title %}base{% endblock %}</title>
    <link rel="stylesheet" href="/static/electronic/style.css" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
    li{
    display: inline;
    }


    </style>
</head>
<body>
<nav class="navbar-fixed-top">
    <ul class="masthead-brand">
        <li><a href="{% url 'electronic:home' %}">Home</a></li>
        <li><a href="{% url 'electronic:contact' %}">Contact</a></li>
        <li><a href="{% url 'electronic:about' %}">About</a></li>
        <li style="float:right"><a class="active" href="{% url 'electronic:logout_user' %}">Logout</a></li>
    </ul>
</nav>
<br>
<br>
<div class="container">
    <h2 style="text-align: center;">
        Electronic ID Site
    </h2>
    <p style="text-align: center;">
        get you electronic identification info...
    </p>
</div>


{% block content %}

{% endblock %}


</body>
</html>

electronic/templates/electronic/contact.html
{% extends 'electronic/base.html' %}
{% block title %}contact{% endblock %}

<body>
{% block content %}

<div class='container'>
    <header>
        <h1>Send us a suggestion!</h1>
    </header>
    <div class='name'>
        <input class='first' placeholder='First Name' type='text'>
        <input class='last' placeholder='Last Name' type='text'>
    </div>
    <div class='contact'>
        <input class='email' placeholder='E-mail Address' type='text'>
    </div>
    <div class='message'>
        <textarea placeholder='Your Suggestions Here!'></textarea>
    </div>
    <footer>
        <button>Send Suggestion</button>
    </footer>
</div>
{% endblock %}
</body>
</html>

electronic/templates/electronic/get_new_id.html
{% extends 'electronic/base.html' %}

{% block title %}get_new_id{% endblock %}

{% block content %}
<div class="container">
    <div class="col-md-12" style="text-align: center;">


        <h3>Fill in the New ID Application Form</h3>
        <p>Kindly use legitimate credentials as contained in your birth certificate!</p>

        <form id="get_id form" action="{% url 'electronic:do_register' %}" method="post">
            {% csrf_token %}
            <label for="firstname">First Name</label>
            <br>
            <input required type="text" name="fname">
            <br>
            <label for="secondname">Second Name</label>
            <br>
            <input required type="text" name="sname">
            <br>
            <label for="thirdname">Last Name</label>
            <br>
            <input required type="text" name="tname">
            <br>
            <label for="dateofbirth">Date of Birth</label>
            <br>
            <input required type="date" name="date_of_birth">
            <br>
            <label for="gender">Gender</label>
            <br>
            <div style="text-align: center">
                <input type="radio" name="gender" value="male"> Male
                <br>
                <input type="radio" name="gender" value="female">Female
                <br>
                <input type="radio" name="gender" value="other" checked> Other
                <br>
            </div>
            <label for="districtofbirth">District of Birth</label>
            <br>
            <input required type="text" name="district_of_birth">
            <br>
            <br>
            <button type="submit" onclick="alert('Thank you for using our services')">Submit</button>

        </form>

    </div>
</div>

{% endblock %}

electronic/templates/electronic/home.html
{% extends 'electronic/base.html' %}

{% block title %}home{% endblock %}

{% block content %}

<div class="jumbotron" id="up_info">
        <h2 style="text-align: center;">Welcome to E-ID Page</h2>
        <p style="text-align: center;">This is your own personal Huduma assistant. Get information about your electronic identification here.For more information about the services offered...</p>
        <p style="text-align: center;"><a class="btn btn-primary btn-lg" href="{% url 'electronic:about' %}" role="button">Learn more &raquo;</a></p>
</div>

<div class="jumbotron">
    <!-- Example row of columns -->
    <div class="row">
        <div class="col-md-4">
            <h2>Apply For New Id</h2>
            <p>Here you can apply for a new electronic identification card. You will be prompted to enter some personal details. Kindly give accurate and legitimate details as this details will be used as given in identifying you. There are some requirements that have to be met before you can be allowed to apply for the identification card</p>
            <p><a class="btn btn-default" href="{% url 'electronic:get_id' %}" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>Replace Lost Id</h2>
            <p>Here you will be able to replace your lost electronic identification card. You can also apply for a new electronic one if the lost identification card was the old one. This is required of only the persons who had ownership of an identification card. You will be asked for your details.</p>
            <p><a class="btn btn-default" href="{% url 'electronic:get_id_info' %}" role="button">View details &raquo;</a></p>
        </div>
        <div class="col-md-4">
            <h2>ID Status</h2>
            <p>Here you can check your ID Status which includes correct information, matching details, you can check the government services that you can access using your electronic identification card. You can also change details about the information contained in your acquired identification card</p>
            <p><a class="btn btn-default" href="{% url 'electronic:id_stat' %}" role="button">View details &raquo;</a></p>
        </div>
    </div>

    <hr>

    <footer>
        <p>&copy; electronic</p>
    </footer>
</div>
<!-- home content goes here -->

{% endblock %}

electronic/templates/electronic/id_status.html
{% extends 'electronic/base.html' %}

{% block title %}replace_id{% endblock %}

{% block content %}

<div class="container">
    <div class="row text-center">
        <div class=" col-md-4  text-center">

        <!--
        <h3>Get your Identification Card Information Here!</h3>
        <p>Kindly use your ID Number and password here! -->
        {% if request.user.person.id_status %}
                <div id="success_status" class="text-center" >
                     Your ID has been processed!
                </div>
        {% else%}
                <div id="not_ready" class=" text-center ">
                     Your Id is being processed!
                 </div>
        {% endif%}
        </div>
    </div>
</div>


{% endblock %}alafu

electronic/templates/electronic/landing.html
<!DOCTYPE html>
<html>

<head>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css"
          integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <meta charset="utf-8">
    <title>{% block title %}base{% endblock %}</title>
    <link rel="stylesheet" href="/static/electronic/style.css" type="text/css">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <style>
    li{
    display: inline;
    }

    </style>
</head>

<body>


<nav class="navbar-fixed-top">
    <ul class="masthead-brand">
        <li><a href="{% url 'electronic:login' %}">Home</a></li>
        <li><a href="{% url 'electronic:login' %}">News</a></li>
        <li><a href="{% url 'electronic:login' %}">Contact</a></li>
        <li><a href="{% url 'electronic:login' %}">About</a></li>
        <li style="float:right"><a class="active" href="{% url 'electronic:logout_user' %}">Logout</a></li>
    </ul>
</nav>

<div class="container">
    <h2 style="text-align: center;">Electronic ID Site</h2>
    <p style="text-align: center;">
        get you electronic identification info...
    </p>
</div>


{% block content %}

{% endblock %}


</body>

<br>
<br>
    <footer style="text-align: center;">
        <p>&copy; electronic</p>
    </footer>
</html>

electronic/templates/electronic/login.html
{% extends 'electronic/landing.html' %}

{% block title %}login{% endblock %}


{% block content %}
<div class="container" id="bad">
    <div class="col-md-12" style="text-align: center;">

        <h2>Welcome</h2>
        <p>You can log in here</p>
        <p class="text-danger">{{ error_msg }}</p>

        <form id="login-form " action="{% url 'electronic:login' %}" method="post">
            {% csrf_token %}
            <label for="username">Username</label>
            <br>
            <input required type="text" id="username" name="username">
            <br>
            <label for="password">Password</label>
            <br>
            <input required type="password" id="password" name="password">
            <br>
            <br>

            <button type="submit" name="login" value="login">Login</button>
        <p>Don't have an account?<br><a class="" href="{% url 'electronic:registration_form' %}" role="">Register Here &raquo;</a></p>
            <div class="checkbox ">
                <label>
                    <input required type="checkbox" id="blankCheckbox" value="option1" aria-label="...">
                </label>
                <p  style="text-color:black;">I agree to Terns & Conditions</p>

            </div>
        </form>
    </div>
</div>

{% endblock %}

electronic/templates/electronic/registration_form.html
{% extends 'electronic/landing.html' %}

{% block title %}registration_form{% endblock %}


{% block content %}
<div class="container">
    <div class="col-md-12" style="text-align: center;">
        <!--  <form id="login-form " action="{% url 'electronic:registration_form' %}" method="post">
           <!--   {{ form.as_p }}
              <button type="submit" name="register" value="registration">Register</button>

          </form> -->
        <h2>Welcome</h2>
        <p>You can register in here</p>
        <p class="text-danger">{{ error_msg }}</p>
        {% csrf_token %}

        <form id="login-form " action="{% url 'electronic:account_register' %}" method="post">
            {% csrf_token %}
            <label for="username">User Name</label>
            <br>
            <input required type="text" id="username" name="username">
            <br>
            <label for="username">Email</label>
            <br>
            <input required type="text" id="email" name="email">
            <br>
            <label for="password">Password</label>
            <br>
            <input required type="password" id="password" name="password">
            <br>
            <br>

            <button type="submit" name="login" value="login">Register</button>

            <div class="checkbox ">
                <label>
                    <input type="checkbox" id="blankCheckbox" value="option1" aria-label="...">
                </label>
                <p style="text-color:black;">I agree to Terns & Conditions</p>

            </div>
        </form>

    </div>
</div>

{% endblock %}

electronic/templates/electronic/replace_confirmation.html
{% extends 'electronic/base.html' %}

{% block title %}replace_confirmation{% endblock %}

{% block content %}

<div class="container">
    <div class="col-md-12" style="text-align: center;">
        <h3>info for id {{ id_info.id_number }} </h3>
        <p>first name{{id_info.first_name }}</p>
        <p>second name {{ id_info.second_name }}</p>
        <p>third name {{ id_info.third_name }}</p>
        <p>district_of_birth {{ id_info.district_of_birth }}</p>
        <p>date_of_birth {{ id_info.date_of_birth }}</p>
        <p>gender {{ id_info.gender }}</p>
        <form id="get_id form" action="{% url 'electronic:do_replace'%}" method="post">
            {% csrf_token %}
            <label for="phone_number">Phone Number</label>
            <br>
            <input required type="text" name="PhoneNumber">
            <br>
            <label for="idno"></label>
            <br>
            <input required value="{{ id_info.id_number }}" type="hidden" name="idno">
            <br>
            <button type="submit" onclick="alert('You request for ID replacement has been received')">Request</button>
            <br>
        </form>

    </div>
</div>

{% endblock %}